# This is a basic workflow to help you get started with Actions

name: "SOA Workflow"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Validate branch name
        run: |
          branch_name=${{ steps.get_branch_name.outputs.branch }}
          echo "Current branch: $branch_name"

          # Expresión regular para validar el nombre de la rama
          if [[ ! $branch_name =~ ^feature\/[a-zA-Z0-9._-]+$ ]]; then
            echo "Branch name does not match the required pattern."
            exit 1
          fi
          
  check-comments:
    name: "Run Check Comments"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Find Java files with single-line comments
        run: |
          if grep -rn '//' --include='*.java' .; then exit 1; else exit 0; fi
        continue-on-error: false

      - name: Find Java files with block comments
        run: |
          if grep -rn '/\*' --include='*.java' .; then exit 1; else exit 0; fi
        continue-on-error: false

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check-comments

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run tests
      run: |
        ./gradlew tests